### ISSUE TITLE
Add headimgurl to list of User functions

### ISSUE THREAD

**Issue by reyaan-boltman** [garbetjie/wechat-php#5]
Garbetjie\WeChatClient\Users\User.php

Need to access ["headimgurl"]

**Comment by garbetjie** [comment]
This has been fixed, along with some backwards-compatible changes having been made on the user's object.

See https://github.com/garbetjie/wechat-php/commit/a40624bfcfb52cd452997794788d29be6bde37d6 for the changes made.
