### ISSUE TITLE
When sending push messages, error codes aren't handled correctly.

### ISSUE THREAD

**Issue by garbetjie** [garbetjie/wechat-php#6]
When I've hit my API limit, this is returned but no exception is thrown:

```
{
    "errcode": 45047,
    "errmsg": "out of response count limit hint: [2UuwHa0680age8]"
}
```

When the user hasn't communicated in the last 48 hours (or the user has unsubscribed), this is returned and no exception is thrown:

```
{
    "errcode": 45015,
    "errmsg": "response out of time limit or subscription is canceled hint: [ynzh1a0039ge12]"
}
```

**Comment by DAks34** [comment]
Hi even I got the same error message 
errmsg": "out of response count limit hint: [2UuwHa0680age8]" 
what is the reason for that

**Comment by garbetjie** [comment]
@DAks34 If I recall correctly, you can only send a limited number of push notifications. This probably means you've hit that limit.

**Comment by Chiragsorathiya** [comment]
i have same problem.

**Comment by Chiragsorathiya** [comment]
got any solution ?

**Comment by garbetjie** [comment]
@Chiragsorathiya I have nothing more than the official WeChat return code documentation at https://developers.weixin.qq.com/doc/offiaccount/en/Getting_Started/Global_Return_Code.html. From the message given, it seems like it has either been more than 48 hours since the user interacted with your Official Account, or they are no longer subscribed to your Official Account. This might be why you can't send them a push message.

I don't actively work with WeChat anymore (and haven't for a few years), so I'm afraid I can't be much help.

**Comment by Chiragsorathiya** [comment]
@garbetjie thanks for replay 
But i send a message to manually to user and user to official account for user interaction and then try again to call we chat sending message API but i getting same error. i tried many solution but no one is working
